/**
 * Generate SDK Theme Data
 * 
 * Single script that generates themes-data.ts containing:
 * 1. BASE_CSS - Layout styles from src/ui/styles.css
 * 2. Theme JSON data - From src/themes/*.json
 * 
 * This is the ONLY generation script. Zero maintenance cost - 
 * SDK uses the exact same source files as the Chrome plugin.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const THEMES_DIR = path.resolve(__dirname, '../../src/themes');
const STYLES_CSS = path.resolve(__dirname, '../../src/ui/styles.css');
const OUTPUT_FILE = path.resolve(__dirname, '../src/themes-data.ts');

/**
 * Read all JSON files from a directory
 */
function readJsonDir(dirPath) {
  const files = fs.readdirSync(dirPath).filter(f => f.endsWith('.json'));
  const result = {};
  for (const file of files) {
    const id = path.basename(file, '.json');
    const content = JSON.parse(fs.readFileSync(path.join(dirPath, file), 'utf-8'));
    result[id] = content;
  }
  return result;
}

/**
 * Extract #markdown-content related CSS rules from styles.css
 */
function extractBaseStyles() {
  const css = fs.readFileSync(STYLES_CSS, 'utf-8');
  
  // Simple CSS parser - extract rules by matching selectors
  const rules = [];
  let depth = 0;
  let currentRule = '';
  let inRule = false;
  
  for (let i = 0; i < css.length; i++) {
    const char = css[i];
    
    if (char === '{') {
      depth++;
      if (depth === 1) {
        inRule = true;
      }
      currentRule += char;
    } else if (char === '}') {
      currentRule += char;
      depth--;
      if (depth === 0 && inRule) {
        // Check if this rule is for #markdown-content
        const selector = currentRule.split('{')[0].trim();
        if (selector.includes('#markdown-content') && 
            !selector.includes('@import') &&
            !selector.includes('@media')) {
          rules.push(currentRule.trim());
        }
        currentRule = '';
        inRule = false;
      }
    } else {
      currentRule += char;
    }
  }
  
  return rules;
}

/**
 * Main generation function
 */
function generate() {
  console.log('📦 Generating themes-data.ts...');

  // 1. Extract CSS from styles.css
  const cssRules = extractBaseStyles();
  console.log(`  ✓ Extracted ${cssRules.length} CSS rules from styles.css`);

  // 2. Read all theme JSON data
  const registry = JSON.parse(fs.readFileSync(path.join(THEMES_DIR, 'registry.json'), 'utf-8'));
  const fontConfig = JSON.parse(fs.readFileSync(path.join(THEMES_DIR, 'font-config.json'), 'utf-8'));
  const presets = readJsonDir(path.join(THEMES_DIR, 'presets'));
  const colorSchemes = readJsonDir(path.join(THEMES_DIR, 'color-schemes'));
  const layoutSchemes = readJsonDir(path.join(THEMES_DIR, 'layout-schemes'));
  const tableStyles = readJsonDir(path.join(THEMES_DIR, 'table-styles'));
  const codeThemes = readJsonDir(path.join(THEMES_DIR, 'code-themes'));

  // 3. Generate TypeScript content
  const content = `/**
 * Auto-generated SDK Theme Data
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-themes.js
 * 
 * Contains:
 * - BASE_CSS: Layout styles from src/ui/styles.css
 * - Theme JSON: All theme configs from src/themes/
 * 
 * Run "npm run build" to regenerate.
 */

// ============================================================================
// Base CSS (from src/ui/styles.css)
// ============================================================================

/**
 * Base CSS for markdown rendering.
 * Contains layout/structural styles - colors/fonts are applied by themes.
 */
export const BASE_CSS = \`
${cssRules.join('\n\n')}
\`;

let baseStylesInjected = false;

/**
 * Inject base styles into the document (only once)
 */
export function injectBaseStyles(): void {
  if (baseStylesInjected || typeof document === 'undefined') return;
  
  const existing = document.getElementById('sdk-base-styles');
  if (existing) {
    baseStylesInjected = true;
    return;
  }
  
  const style = document.createElement('style');
  style.id = 'sdk-base-styles';
  style.textContent = BASE_CSS;
  document.head.appendChild(style);
  baseStylesInjected = true;
}

// ============================================================================
// Type Definitions
// ============================================================================

export interface ThemeRegistryEntry {
  id: string;
  file: string;
  category: string;
  featured?: boolean;
  order?: number;
}

export interface ThemeCategory {
  name: string;
  name_en?: string;
  description?: string;
  description_en?: string;
  order?: number;
  [key: string]: unknown;
}

export interface ThemeRegistry {
  version: string;
  themes: ThemeRegistryEntry[];
  categories: Record<string, ThemeCategory>;
  recommendations?: Record<string, string>;
  [key: string]: unknown;
}

export interface FontScheme {
  body: { fontFamily: string };
  headings: { fontFamily?: string; fontWeight?: string; [key: string]: unknown };
  code: { fontFamily: string };
}

export interface ThemePreset {
  id: string;
  name: string;
  name_en?: string;
  description?: string;
  description_en?: string;
  author?: string;
  version?: string;
  fontScheme: FontScheme;
  layoutScheme: string;
  colorScheme: string;
  tableStyle: string;
  codeTheme: string;
  diagramStyle?: 'normal' | 'handDrawn';
  [key: string]: unknown;
}

export interface ColorScheme {
  id?: string;
  name?: string;
  description?: string;
  description_en?: string;
  text: { primary: string; secondary: string; tertiary?: string };
  background: { page: string; content?: string; code: string };
  accent: {
    link: string;
    linkHover: string;
    primary?: string;
    secondary?: string;
  };
  blockquote: { border: string; background?: string };
  table: {
    border: string;
    headerBackground: string;
    headerText: string;
    zebraEven: string;
    zebraOdd: string;
  };
  [key: string]: unknown;
}

export interface LayoutScheme {
  id?: string;
  name?: string;
  body: { fontSize: string; lineHeight: string };
  headings: {
    [key: string]: {
      fontSize: string;
      lineHeight?: string;
      marginTop?: string;
      marginBottom?: string;
      fontWeight?: string;
    };
  };
  paragraph?: { marginTop?: string; marginBottom?: string };
  [key: string]: unknown;
}

export interface TableStyle {
  id?: string;
  name?: string;
  border?: {
    all?: { style: string; width: string };
    headerTop?: { style: string; width: string };
    headerBottom?: { style: string; width: string };
    rowBottom?: { style: string; width: string };
    lastRowBottom?: { style: string; width: string };
  };
  header: { fontWeight?: string; fontSize?: string };
  cell: { padding: string };
  zebra?: { enabled: boolean };
}

export interface CodeTheme {
  id?: string;
  name?: string;
  description?: string;
  description_en?: string;
  foreground?: string;
  colors?: Record<string, string>;
  keyword?: string;
  string?: string;
  number?: string;
  comment?: string;
  function?: string;
  variable?: string;
  tag?: string;
  attribute?: string;
  class?: string;
  [key: string]: unknown;
}

export interface FontEntry {
  name: string;
  type: string;
  webFallback: string;
  loadPriority?: string;
  docx?: { ascii: string; eastAsia: string };
}

export interface FontConfig {
  version: string;
  fonts: Record<string, FontEntry>;
  fallbacks: Record<string, string[]>;
  docx?: { ascii: string; eastAsia: string };
  [key: string]: unknown;
}

// ============================================================================
// Theme Data
// ============================================================================

export const THEME_REGISTRY: ThemeRegistry = ${JSON.stringify(registry, null, 2)};

export const FONT_CONFIG: FontConfig = ${JSON.stringify(fontConfig, null, 2)};

export const THEME_PRESETS: Record<string, ThemePreset> = ${JSON.stringify(presets, null, 2)};

export const COLOR_SCHEMES: Record<string, ColorScheme> = ${JSON.stringify(colorSchemes, null, 2)};

export const LAYOUT_SCHEMES: Record<string, LayoutScheme> = ${JSON.stringify(layoutSchemes, null, 2)};

export const TABLE_STYLES: Record<string, TableStyle> = ${JSON.stringify(tableStyles, null, 2)};

export const CODE_THEMES: Record<string, CodeTheme> = ${JSON.stringify(codeThemes, null, 2)};
`;

  // Write output file
  fs.writeFileSync(OUTPUT_FILE, content, 'utf-8');
  
  const stats = {
    cssRules: cssRules.length,
    presets: Object.keys(presets).length,
    colorSchemes: Object.keys(colorSchemes).length,
    layoutSchemes: Object.keys(layoutSchemes).length,
    tableStyles: Object.keys(tableStyles).length,
    codeThemes: Object.keys(codeThemes).length,
  };
  
  console.log(`  ✓ Generated themes-data.ts`);
  console.log(`    - ${stats.cssRules} CSS rules`);
  console.log(`    - ${stats.presets} theme presets`);
  console.log(`    - ${stats.colorSchemes} color schemes`);
  console.log(`    - ${stats.layoutSchemes} layout schemes`);
  console.log(`    - ${stats.tableStyles} table styles`);
  console.log(`    - ${stats.codeThemes} code themes`);
  console.log('\n✅ Generation complete!\n');
}

generate();
